# For RTX3090 users
name: cosypose
channels:
   - conda-forge
   - pytorch
dependencies:
  - python
  - pinocchio
  - assimp
  - pytorch
  - cudatoolkit=11.3
  - torchvision
  - cudnn
  - rclone
  - gxx_linux-64
  - git-lfs
  - ffmpeg
  - bzip2
  - git
  - cmake
  - pip
  - numpy
  - pillow
  - ipython
  - pip:
      - ./deps/bullet3
      - ./deps/job-runner
      - imageio
      - simplejson
      - opencv-python
      - opencv-contrib-python
      - torchnet
      - tqdm
      - lxml
      - transforms3d
      - distributed
      - joblib
      - pandas
      - xarray==0.14.1
      - pyarrow
      - matplotlib
      - bokeh==2.4.3
      - plyfile
      - trimesh
      - pycollada
      - shapely
      - wget
      - pypng
      - PyOpenGL
      - Cython
      - ipdb
      - colorama
      - scikit-video
      - scikit-image
      - scikit-learn
      - pyyaml
      - ipykernel
      - scipy
      - pywavefront
      - jupyter-client
      - jupyter-core
      - jupyter-server-proxy
      - jupyterlab
      - jupyterlab-server
      - dask
      - dask-jobqueue
      - seaborn
